# EssentialsBank Configuration File
# -----------------------------------
# Configure the language. Native support for: 'en' (English), 'es' (Spanish).
locale: 'en'

# Name of the server bank account (internally created as an NPC in Essentials)
bank-account-name: 'ServerBank'