name: EssentialsBank
version: '1.4.0'
main: net.essentialsx.bank.EssentialsBank
api-version: '1.13'
depend: [Essentials, Vault]
description: A centralized bank plugin that acts natively with EssentialsX and Vault.
commands:
  bank:
    description: Main commands for the server bank.
    aliases: [banco, serverbank]
    permission: essentialsbank.use
permissions:
  essentialsbank.use:
    description: Allows using basic bank commands.
    default: true
  essentialsbank.admin:
    description: Allows managing the server bank.
    default: op